name = "connectors"
version = "0.4.4"
[dependencies]
diodes = { git = "JITx-Inc/diodes", version = "0.2.0" }
jsl = { git = "JITx-Inc/jsl", version = "0.10.1" }
mechanical = { git = "JITx-Inc/mechanical", version = "0.3.0" }
